title: Nicholas C. Sim
logo: https://avatars.githubusercontent.com/u/66676750?v=4
description: Applied Econometrics | Policy Evaluation | Trade and Development
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
