title: Nicholas Sim's Teaching Page
logo: https://avatars.githubusercontent.com/u/66676750?v=4
description: Welcome! I am an economist by training and I teach ANL501 Data Visualisation and Storytelling at the Singapore Univeristy of Social Sciences.
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
